spring:
  application:
    name: consumer-order
server:
  port: 80
eureka:
  instance:
    instance-id: consumer-order
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka