spring:
  application:
    name: consumer-order
server:
  port: 80
eureka:
  instance:
    instance-id: consumer-order-openfeign
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka
logging:
  level:
    # feign以什么级别监控哪个接口
    com.lemonzuo.service.PaymentFeignService: debug