server:
  port: 83
spring:
  application:
    name: order-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
# 需要访问的服务提供者地址
service-url:
  nacos-user-service: http://payment-nacos-provider