server:
  port: 9002
spring:
  application:
    name: payment-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务地址
management:
  endpoints:
    web:
      exposure:
        include: "*"