spring:
  application:
    name: consumer-order
server:
  port: 80
eureka:
  instance:
    instance-id: consumer-order-openfeign
    prefer-ip-address: true
  client:
    service-url:
      # defaultZone: http://127.0.0.1:7001/eureka, http://127.0.0.1:7002/eureka
      defaultZone: http://127.0.0.1:7001/eureka
ribbon:
  # 建立连接后从服务器读取可用资源所用时间
  read-timeouot: 5000
  # 建立连接所用时间，适用于网络连接正常情况下，两端连接所用时间
  connect-timeout: 5000

feign:
  hystrix:
    enabled: true